### ISSUE TITLE
[SS] No way of returning to home

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/tutorials.ubuntu.com#56] opened 2017-01-16 10:41 UTC
Once entered a tutorial on a mobile. There is no way to leaving the tutorial and return to the home screen. 

I would expect a home link at the top of the menu in the burger slide out.

**Comment by magdalena-mirowicz** [comment] 2017-01-16 10:49
duplicate of #46, closing

**Closed by magdalena-mirowicz** 2017-01-16 10:49 UTC
